Removed the data processor.
chathurapriyankara/JavaFXMaven pull request #1
Opened 2021-12-20 23:57 UTC by chathurapriyankara

2021-12-20 23:57 UTC, chathurapriyankara commented
This PR is fine. Please merge this.

2021-12-21 00:00 UTC, chathurapriyankara commented
This PR is fine. Need to merge.

2021-12-21 02:05 UTC, chathurauok commented on src/main/java/server/ServerThread.java
> -    private DataProcessor dataProcessor;
Why did you remove the data processor ?

2021-12-21 02:05 UTC, chathurauok commented on src/main/java/server/ServerThread.java
> -        try (BufferedReader reader = new BufferedReader(new InputStreamReader(socket.getInputStream()))) {
Why did you change the try with resources ?

2021-12-21 04:45 UTC, DhanJaya commented on src/main/java/server/ServerThread.java
> -        try (BufferedReader reader = new BufferedReader(new InputStreamReader(socket.getInputStream()))) {
Following the best practices

2021-12-21 04:46 UTC, chathurapriyankara commented on src/main/java/server/ServerThread.java
> -        try (BufferedReader reader = new BufferedReader(new InputStreamReader(socket.getInputStream()))) {
Reply

2021-12-21 05:23 UTC, DhanJaya commented on src/main/java/server/ServerThread.java
> -    private DataProcessor dataProcessor;
Since its not used

2021-12-21 05:24 UTC, chathurapriyankara commented on src/main/java/server/ServerThread.java
> -        try (BufferedReader reader = new BufferedReader(new InputStreamReader(socket.getInputStream()))) {
Reply2

2021-12-21 05:28 UTC, chathurauok requested changes

2021-12-21 05:28 UTC, chathurauok commented on src/main/java/server/ServerThread.java
> -import parser.Food;
Add this back.

2021-12-21 11:45 UTC, chathurauok commented on src/main/java/server/ServerThread.java
> -import java.util.ArrayList;
You need the array list ?

2021-12-21 11:46 UTC, chathurauok reviewed
done

2021-12-25 11:09 UTC, merged